### ISSUE TITLE
Compatibility with Meteor 2.6

### ISSUE THREAD

**Issue by derwaldgeist** [quavedev/apple-oauth#27]
I tried the new 4.0.0 package with Meteor 2.6.1. It throws an error message in the client console if I want to log-on via the web client:

```
TypeError: ServiceConfiguration.configurations.findOneAsync is not a function
    at getServiceConfiguration (utils.js:18:61)
    at Apple.requestCredential (apple_client.js:33:24)
    at AccountsClient.loginWithApple (apple.js:15:17)
    at AccountsClient.applyLoginFunction (accounts_client.js:112:39)
    at Meteor.loginWithApple (apple.js:23:14)
    at SocialButtons.loginWith (socialButtons.js:36:5)
    at onClick (socialButtons.js:19:31)
    at HTMLUnknownElement.callCallback (modules.js?hash=d20a3205b7058d0fcf3d5804cf1f06359a3081a8:13173:14)
    at Object.invokeGuardedCallbackDev (modules.js?hash=d20a3205b7058d0fcf3d5804cf1f06359a3081a8:13222:16)
    at invokeGuardedCallback (modules.js?hash=d20a3205b7058d0fcf3d5804cf1f06359a3081a8:13284:31)
```

I think that's because Meteor 2.6 does not support findOneAsync yet.

**Comment by derwaldgeist** [comment]
I patched this, using this:

```
  const service = ServiceConfiguration.configurations.findOneAsync
    ? await ServiceConfiguration.configurations.findOneAsync({ service: 'apple' })
    : ServiceConfiguration.configurations.findOne({ service: 'apple' });
```

This allows me to start the Apple sign in process in my web app client.

However, now I am running into this issue on server-side, after the redirection URL has been invoked and the popup was closed:

```
Exception while invoking method 'login' TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at AccountsServer.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1273:17)
    at MethodInvocation.<anonymous> (packages/accounts-oauth/oauth_server.js:55:21)
    at packages/accounts-base/accounts_server.js:594:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1509:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:592:22)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:652:31)
    at MethodInvocation.methodMap.<computed> (packages/montiapm:agent/lib/hijack/wrap_session.js:174:30)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1882:18)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:765:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/montiapm:agent/lib/hijack/wrap_session.js:65:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at Session.sessionProto.protocol_handlers.method (packages/montiapm:agent/lib/hijack/wrap_session.js:64:44)
```

This happens with the original package, without the changes of my own fork (I just patched the async call above). I don't think it's related to the montiapm-wrapper, since it worked without any issues before.

**Comment by derwaldgeist** [comment]
Edit: I am using `<AccountsReactComponent>` from `meteor/meteoreact:accounts` for creating the social sign-in buttons in the web frontend. Maybe these are not compatible to this library anymore?

They construct the loginWithApple call like this:
```js
loginWith = service => {
    let _service = service[0].toUpperCase() + service.substr(1)

    if (service === 'meteor-developer') {
      _service = 'MeteorDeveloperAccount'
    }

    const options = AccountsReact.config.oauth[service] || {}
    Meteor['loginWith' + _service](options, err => {
      if (!err) {
        const { onLoginHook } = this.props.defaults
        if (onLoginHook) {
          onLoginHook()
        }
      }
    })
  }
```
Maybe there's something missing here now?

**Comment by derwaldgeist** [comment]
Ok, I was able to use the library in 2.6 with version 3.1.1. Seems as if 4.0.0 is not compatible with 2.6 (yet).
